//
//  FloatcutOperator.m
//  Floatcut
//
//  Flycut by Gennadiy Potapov and contributors. Based on Jumpcut by Steve Cook.
//  Copyright 2011 General Arcade. All rights reserved.
//
//  This code is open-source software subject to the MIT License; see the homepage
//  at <https://github.com/TermiT/Flycut> for details.
//

// FloatcutOperator owns and interacts with the FloatcutStores, providing
// manipulation of the stores.

#import <Foundation/Foundation.h>
#import "FloatcutOperator.h"

#ifdef FLOATCUT_MAC
#import "AppController.h"
#endif

@implementation FloatcutOperator {
	NSDateFormatter *dateFormatterForFilename;
	NSDateFormatter *dateFormatterForDirectory;
}

static const NSTimeInterval FloatcutDeferredSaveDelay = 0.75;

- (id)init
{
	[[NSUserDefaults standardUserDefaults] registerDefaults:[NSDictionary dictionaryWithObjectsAndKeys:
		[NSNumber numberWithInt:40],
		@"rememberNum",
        [NSNumber numberWithInt:40],
        @"favoritesRememberNum",
		[NSNumber numberWithInt:1],
		@"savePreference",
        [NSDictionary dictionary],
        @"store",
        [NSNumber numberWithBool:YES],
        @"skipPasswordFields",
		[NSNumber numberWithBool:YES],
		@"skipPboardTypes",
		@"PasswordPboardType,org.nspasteboard.TransientType,org.nspasteboard.ConcealedType,org.nspasteboard.AutoGeneratedType,com.agilebits.onepassword",
		@"skipPboardTypesList",
		[NSNumber numberWithBool:NO],
		@"skipPasswordLengths",
		@"12, 20, 32",
		@"skipPasswordLengthsList",
		[NSNumber numberWithBool:NO],
		@"revealPasteboardTypes",
        [NSNumber numberWithBool:NO],
        @"removeDuplicates",
        [NSNumber numberWithBool:NO],
        @"pasteMovesToTop",
        nil]];

	return self;
}

- (void)awakeFromNibDisplaying:(int) dispNum withDisplayLength:(int) dispLength withSaveSelector:(SEL) selector forTarget:(NSObject*) target
{
	displayNum = dispNum;
	displayLength = dispLength;
	saveSelector = selector;
	saveTarget = target;

	// Initialize the FloatcutStore
	[self initializeStoresAndLoadContents];

	// Stack position starts @ 0 by default
	stackPosition = favoritesStackPosition = stashedStackPosition = 0;
}

-(FloatcutStore*) allocInitFloatcutStoreRemembering:(int) remembering
{
	return [[FloatcutStore alloc] initRemembering:remembering
									 displaying:displayNum
							  withDisplayLength:displayLength];
}

-(void) initializeStores
{
	// Fixme - These stores are not released anywhere.
	if ( !clippingStore )
	{
		clippingStore = [self allocInitFloatcutStoreRemembering:[[NSUserDefaults standardUserDefaults] integerForKey:@"rememberNum"]];
		clippingStore.deleteDelegate = self;
	}
	else
	{
		[clippingStore setDisplayNum:displayNum];
		[clippingStore setDisplayLen:displayLength];
	}

	if ( ! favoritesStore )
	{
		favoritesStore = [self allocInitFloatcutStoreRemembering:[[NSUserDefaults standardUserDefaults] integerForKey:@"favoritesRememberNum"]];
		favoritesStore.deleteDelegate = self;
	}
	else
	{
		[favoritesStore setDisplayNum:displayNum];
		[favoritesStore setDisplayLen:displayLength];
	}

	stashedStore = NULL;
}

-(void) initializeStoresAndLoadContents
{
	[self initializeStores];

	// If our preferences indicate that we are saving, load the dictionary from the saved plist
	// and use it to get everything set up.
	if ( [[NSUserDefaults standardUserDefaults] integerForKey:@"savePreference"] >= 1 ) {
		[self loadEngineFromPList];
	}
}

-(void) willShowPreferences
{
	issuedRememberResizeWarning = NO;
}

-(int) setRememberNum:(int)newRemember forPrimaryStore:(BOOL) isPrimaryStore
{
	int oldRemeber = [self rememberNum];

	// Ensure that we don't remember zero or fewer clippings.
	if ( newRemember <= 0 )
	{
		newRemember = oldRemeber;
		if ( newRemember <= 0 )
			newRemember = 40;
	}

	if ( newRemember < [self jcListCount] &&
		! issuedRememberResizeWarning &&
		! [[NSUserDefaults standardUserDefaults] boolForKey:@"stifleRememberResizeWarning"]
		) {

		NSString *choice = [self delegateAlertWithMessageText:@"Resize Stack"
											  informationText:@"Resizing the stack to a value below its present size will cause clippings to be lost."
												 buttonsTexts:@[@"Resize", @"Cancel", @"Don't Warn Me Again"]];
		if ( [choice isEqualToString:@"Cancel"] ) {
			// Cancel - Change to prior setting.
			newRemember = oldRemeber;
			if ( isPrimaryStore ) {
				[[NSUserDefaults standardUserDefaults] setValue:[NSNumber numberWithInt:newRemember]
														 forKey:@"rememberNum"];
			} else {
				[[NSUserDefaults standardUserDefaults] setValue:[NSNumber numberWithInt:newRemember]
														 forKey:@"favoritesRememberNum"];
			}
		} else if ( [choice isEqualToString:@"Don't Warn Me Again"] ) {
			// Don't Warn Me Again
			[[NSUserDefaults standardUserDefaults] setValue:[NSNumber numberWithBool:YES]
													 forKey:@"stifleRememberResizeWarning"];
		} else {
			// Resize
			issuedRememberResizeWarning = YES;
		}
	}

	// Set the value.
	[clippingStore setRememberNum:newRemember];

	return newRemember;
}

-(void)toggleToFromFavoritesStore
{
    [self setFavoritesStoreSelected:![self favoritesStoreIsSelected]];
}

-(bool)favoritesStoreIsSelected
{
    return clippingStore == favoritesStore;
}

-(void)setFavoritesStoreSelected:(bool)selected
{
	if (selected == [self favoritesStoreIsSelected])
		return;

	if (selected)
		[self switchToFavoritesStore];
	else
		[self restoreStashedStore];
}

-(void)switchToFavoritesStore
{
	if ([self favoritesStoreIsSelected])
		return;

    stashedStore = clippingStore;
    clippingStore = favoritesStore;
    stashedStackPosition = stackPosition;
    stackPosition = favoritesStackPosition;
}

- (bool)restoreStashedStore
{
    if (NULL != stashedStore)
    {
        clippingStore = stashedStore;
        stashedStore = NULL;
        favoritesStackPosition = stackPosition;
        stackPosition = stashedStackPosition;
        return YES;
    }
    return NO;
}

- (NSString*)getPasteFromStackPosition
{
	if ( [clippingStore jcListCount] > stackPosition ) {
		return [self getPasteFromIndex: stackPosition];
	}
	return nil;
}

- (bool)saveFromStack
{
    return [self saveFromStackWithPrefix:@""];
}

- (bool)saveFromStackWithPrefix:(NSString*) prefix
{
	return [self saveFromStore:clippingStore atIndex:stackPosition withPrefix:prefix];
}

- (bool)saveFromStore:(FloatcutStore*)store atIndex:(int)index withPrefix:(NSString*) prefix
{
    if ( [store jcListCount] > index ) {
        FloatcutClipping *clipping = [store clippingAtPosition:index];
        // Get text from clipping store.
        NSString *pbFullText = [self clippingStringWithCount:index inStore:store];
        pbFullText = [pbFullText stringByReplacingOccurrencesOfString:@"\r" withString:@"\r\n"];

        if (!dateFormatterForFilename) {
            // Date formatters are time-expensive to create, so create once and reuse.
            dateFormatterForFilename = [[NSDateFormatter alloc] init];
            [dateFormatterForFilename setDateFormat:@"yyyy-MM-dd 'at' HH.mm.ss"];
        }

        // Get the timestamp string:
        NSDate *currentDate = [NSDate date];
        NSString *dateString = [dateFormatterForFilename stringFromDate:currentDate];

        // Make a file name
        NSString *fileExtension = [clipping isImage] ? @"png" : @"txt";
        NSString *fileName = [NSString stringWithFormat:@"%@%@Clipping %@.%@",
                              prefix, store == favoritesStore ? @"Favorite " : @"", dateString, fileExtension];

        // Make a subdirectory, if doing autosave, to avoid a directory with too many files in it as that can make Finder effectively hang on launch if that directory were the desktop.
        NSString *subdirectoryString = nil;
        if ([prefix isEqualToString:@"Autosave "]) {
            if (!dateFormatterForDirectory) {
                // Date formatters are time-expensive to create, so create once and reuse.
                dateFormatterForDirectory = [[NSDateFormatter alloc] init];
                [dateFormatterForDirectory setDateFormat:@"'Autosave Clippings' yyyy/MM"];
            }
            subdirectoryString = [dateFormatterForDirectory stringFromDate:currentDate];
        }

        NSString *baseDirectoryString = nil;
        NSString *fileNameWithPath = nil;

#ifdef FLOATCUT_MAC
        if ([prefix isEqualToString:@"Autosave "]) {
            NSURL* autoSaveToLocation = [[NSUserDefaults standardUserDefaults] URLForKey:@"autoSaveToLocation"];
            if (autoSaveToLocation) {
                baseDirectoryString = autoSaveToLocation.path;
            }
        } else {
            NSURL* saveToLocation = [[NSUserDefaults standardUserDefaults] URLForKey:@"saveToLocation"];
            if (saveToLocation) {
                baseDirectoryString = saveToLocation.path;
            }
        }
#endif

        if (!fileNameWithPath) {
            // An exact place to save wasn't set (like from a Save panel), so build one.

            if (!baseDirectoryString) {
                // Get the Desktop directory since nothing else was specified.
                NSArray *paths = NSSearchPathForDirectoriesInDomains
                (NSDesktopDirectory, NSUserDomainMask, YES);
                NSString *desktopDirectory = [paths objectAtIndex:0];

                baseDirectoryString = desktopDirectory;
            }

            if (subdirectoryString) {
                // Apply a subdirectory / subdirectories.
                NSString *directoryPath = [NSString stringWithFormat:@"%@/%@",
                                           baseDirectoryString, subdirectoryString];
                [[NSFileManager defaultManager] createDirectoryAtPath:directoryPath
                                          withIntermediateDirectories:YES
                                                           attributes:nil
                                                                error:nil];
                baseDirectoryString = directoryPath;
            }

            // Make a file name to write the data to using the base directory:
            fileNameWithPath = [NSString stringWithFormat:@"%@/%@",
                                baseDirectoryString, fileName];
        }

        // Save content to the file
        if ([clipping isImage]) {
            [[clipping imageData] writeToFile:fileNameWithPath atomically:NO];
        } else {
            [pbFullText writeToFile:fileNameWithPath
                      atomically:NO
                        encoding:NSNonLossyASCIIStringEncoding
                           error:nil];
        }
        return YES;
    }
    return NO;
}

- (bool)saveFromStackToFavorites
{
    if ( clippingStore != favoritesStore && [clippingStore jcListCount] > stackPosition ) {
        // Get text from clipping store.
        [favoritesStore addClipping:[clippingStore clippingAtPosition:stackPosition] ];
        [self clearItemAtStackPosition];
        return YES;
    }
    return NO;
}

-(FloatcutStore *)primaryStore
{
	return [self favoritesStoreIsSelected] ? stashedStore : clippingStore;
}

-(FloatcutClipping *)duplicateClippingPreservingIdentity:(FloatcutClipping *)clipping
{
	FloatcutClipping *duplicate = [[[FloatcutClipping alloc] initWithContents:[clipping contents]
														 withType:[clipping type]
													withImageData:[clipping imageData]
												withDisplayLength:[clipping displayLength]
										 withAppLocalizedName:[clipping appLocalizedName]
											 withAppBundleURL:[clipping appBundleURL]
												withTimestamp:[clipping timestamp]] autorelease];
	[duplicate setIdentifier:[clipping identifier]];
	[duplicate setHasName:[clipping hasName]];
	[duplicate setReceivedFromSync:[clipping receivedFromSync]];
	return duplicate;
}

-(NSSet *)favoriteClippingIdentifiers
{
	NSMutableSet *identifiers = [NSMutableSet setWithCapacity:[favoritesStore jcListCount]];
	for (int index = 0; index < [favoritesStore jcListCount]; index++) {
		NSString *identifier = [[favoritesStore clippingAtPosition:index] identifier];
		if ([identifier length] > 0)
			[identifiers addObject:identifier];
	}
	return identifiers;
}

-(bool)isClippingFavoriteWithIdentifier:(NSString *)identifier
{
	return favoritesStore && [identifier length] > 0 && [favoritesStore indexOfClippingIdentifier:identifier] >= 0;
}

-(bool)toggleFavoriteForClippingWithIdentifier:(NSString *)identifier
{
	FloatcutStore *primaryStore = [self primaryStore];
	int primaryIndex = [primaryStore indexOfClippingIdentifier:identifier];
	if (!primaryStore || primaryIndex < 0)
		return NO;

	int favoriteIndex = [favoritesStore indexOfClippingIdentifier:identifier];
	if (favoriteIndex >= 0) {
		BOOL previousInhibitAutosave = inhibitAutosaveClippings;
		inhibitAutosaveClippings = YES;
		[favoritesStore clearItem:favoriteIndex];
		inhibitAutosaveClippings = previousInhibitAutosave;
		if ([self favoritesStoreIsSelected])
			stackPosition = MIN(stackPosition, MAX(0, [favoritesStore jcListCount] - 1));
		else
			favoritesStackPosition = MIN(favoritesStackPosition, MAX(0, [favoritesStore jcListCount] - 1));
		[self actionAfterListModification];
		return YES;
	}

	FloatcutClipping *clipping = [primaryStore clippingAtPosition:primaryIndex];
	[favoritesStore addClippingPreservingDistinctIdentifier:[self duplicateClippingPreservingIdentity:clipping]];
	if ([favoritesStore indexOfClippingIdentifier:identifier] < 0)
		return NO;

	if ([self favoritesStoreIsSelected])
		stackPosition = 0;
	else
		favoritesStackPosition = 0;
	[self actionAfterListModification];
	return YES;
}

-(bool)moveFavoriteToPrimaryStoreWithIdentifier:(NSString *)identifier
{
	FloatcutStore *primaryStore = [self primaryStore];
	int favoriteIndex = [favoritesStore indexOfClippingIdentifier:identifier];
	if (!primaryStore || favoriteIndex < 0)
		return NO;

	int primaryIndex = [primaryStore indexOfClippingIdentifier:identifier];
	if (primaryIndex > 0) {
		[primaryStore clippingMoveToTop:primaryIndex];
	} else if (primaryIndex < 0) {
		FloatcutClipping *favorite = [favoritesStore clippingAtPosition:favoriteIndex];
		[primaryStore addClippingPreservingDistinctIdentifier:[self duplicateClippingPreservingIdentity:favorite]];
	}

	if ([primaryStore indexOfClippingIdentifier:identifier] != 0)
		return NO;

	BOOL previousInhibitAutosave = inhibitAutosaveClippings;
	inhibitAutosaveClippings = YES;
	[favoritesStore clearItem:favoriteIndex];
	inhibitAutosaveClippings = previousInhibitAutosave;

	if ([self favoritesStoreIsSelected]) {
		stackPosition = MIN(stackPosition, MAX(0, [favoritesStore jcListCount] - 1));
		stashedStackPosition = 0;
	} else {
		stackPosition = 0;
		favoritesStackPosition = MIN(favoritesStackPosition, MAX(0, [favoritesStore jcListCount] - 1));
	}
	[self actionAfterListModification];
	return YES;
}

- (FloatcutClipping*)getClippingFromIndex:(int) position
{
    return [clippingStore clippingAtPosition:position];
}

- (NSString*)getPasteFromIndex:(int) position {
	NSString *clipping = [self getClipFromCount:position];

	if ( [[NSUserDefaults standardUserDefaults] boolForKey:@"pasteMovesToTop"] ) {
		[clippingStore clippingMoveToTop:position];
		stackPosition = 0;

		[self actionAfterListModification];
	}
	return clipping;
}

- (bool)moveClippingAtStackPositionToTop
{
    if (![self stackPositionIsInBounds])
        return NO;

    if (stackPosition != 0)
        [clippingStore clippingMoveToTop:stackPosition];

    stackPosition = 0;
    [self actionAfterListModification];
    return YES;
}

-(NSString*)getClipFromCount:(int)indexInt
{
//    NSString *pbFullText;å
//    NSArray *pbTypes;
    if ( (indexInt + 1) > [clippingStore jcListCount] ) {
        // We're asking for a clipping that isn't there yet
		// This only tends to happen immediately on startup when not saving, as the entire list is empty.
        DLog(@"Out of bounds request to jcList ignored.");
        return nil;
    }
	return [self clippingStringWithCount:indexInt];
}

-(bool)addImageClippingData:(NSData*)imageData ofType:(NSString*)type fromApp:(NSString *)appName withAppBundleURL:(NSString *)bundleURL target:(id)selectorTarget clippingAddedSelector:(SEL)clippingAddedSelector
{
    if (nil == imageData || [imageData length] == 0)
        return NO;

    FloatcutClipping *newClipping = [[FloatcutClipping alloc] initWithContents:@""
                                                                  withType:type
                                                             withImageData:imageData
                                                         withDisplayLength:displayLength
                                                      withAppLocalizedName:appName
                                                          withAppBundleURL:bundleURL
                                                             withTimestamp:[[NSDate date] timeIntervalSince1970]];
    if ([clippingStore jcListCount] == 0 || ![newClipping isEqual:[clippingStore clippingAtPosition:0]]) {
        [clippingStore addClipping:newClipping];
        stackPosition = 0;
        [selectorTarget performSelector:clippingAddedSelector];
        [self actionAfterListModification];
        [newClipping release];
        return YES;
    }

    [newClipping release];
    return NO;
}

-(BOOL)shouldSkip:(NSString *)contents ofType:(NSString *)type fromAvailableTypes:(NSArray<NSString *> *)availableTypes
{
	// Check to see if we are skipping passwords based on length and characters.
	if ( [[NSUserDefaults standardUserDefaults] boolForKey:@"skipPasswordFields"] )
	{
		// Check to see if they want a little help figuring out what types to enter.
		if ( [[NSUserDefaults standardUserDefaults] boolForKey:@"revealPasteboardTypes"] ) {
			[clippingStore addClipping:type ofType:type fromAppLocalizedName:@"Floatcut" fromAppBundleURL:nil atTimestamp:0];
			[self actionAfterListModification];
		}

		__block bool skipClipping = NO;

		// Check the array of types to skip.
		if ( availableTypes && [[NSUserDefaults standardUserDefaults] boolForKey:@"skipPboardTypes"] )
		{
			NSSet *typesToSkip = [NSSet setWithArray: [[[[NSUserDefaults standardUserDefaults] stringForKey:@"skipPboardTypesList"] stringByReplacingOccurrencesOfString:@" " withString:@""] componentsSeparatedByString: @","]];
			NSSet *pasteBoardTypes = [NSSet setWithArray: availableTypes];

			if ( [pasteBoardTypes intersectsSet: typesToSkip] )
				{
						skipClipping = YES;
				};

		}
		if (skipClipping)
			return YES;

		// Check the array of lengths to skip for suspicious strings.
		if ( [[NSUserDefaults standardUserDefaults] boolForKey:@"skipPasswordLengths"] )
		{
			int contentsLength = [contents length];
			NSArray *lengthsArray = [[[[NSUserDefaults standardUserDefaults] stringForKey:@"skipPasswordLengthsList"] stringByReplacingOccurrencesOfString:@" " withString:@""] componentsSeparatedByString: @","];
			[lengthsArray enumerateObjectsUsingBlock:^(id lengthString, NSUInteger idx, BOOL *stop)
			{
				if ( [lengthString integerValue] == contentsLength )
				{
					NSRange uppercaseLetter = [contents rangeOfCharacterFromSet: [NSCharacterSet uppercaseLetterCharacterSet]];
					NSRange lowercaseLetter = [contents rangeOfCharacterFromSet: [NSCharacterSet lowercaseLetterCharacterSet]];
					NSRange decimalDigit = [contents rangeOfCharacterFromSet: [NSCharacterSet decimalDigitCharacterSet]];
					NSRange punctuation = [contents rangeOfCharacterFromSet: [NSCharacterSet punctuationCharacterSet]];
					NSRange symbol = [contents rangeOfCharacterFromSet: [NSCharacterSet symbolCharacterSet]];
					NSRange control = [contents rangeOfCharacterFromSet: [NSCharacterSet controlCharacterSet]];
					NSRange illegal = [contents rangeOfCharacterFromSet: [NSCharacterSet illegalCharacterSet]];
					NSRange whitespaceAndNewline = [contents rangeOfCharacterFromSet: [NSCharacterSet whitespaceAndNewlineCharacterSet]];
					if ( NSNotFound == control.location
						&& NSNotFound == illegal.location
						&& NSNotFound == whitespaceAndNewline.location
						&& NSNotFound != uppercaseLetter.location
						&& NSNotFound != lowercaseLetter.location
						&& NSNotFound != decimalDigit.location
						&& ( NSNotFound != punctuation.location
							|| NSNotFound != symbol.location ) )
					{
						skipClipping = YES;
						*stop = YES;
					}
				}
			}];

			if (skipClipping)
				return YES;
		}
	}
	return NO;
}

-(void)setDisableStoreTo:(bool) value
{
    disableStore = value;
}

-(bool)storeDisabled
{
	return disableStore;
}

-(void)setClippingsStoreDelegate:(id<FloatcutStoreDelegate>) delegate
{
	if ( !clippingStore )
		[self initializeStores];
	clippingStore.delegate = delegate;
}

-(void)setFavoritesStoreDelegate:(id<FloatcutStoreDelegate>) delegate
{
	if ( !favoritesStore )
		[self initializeStores];
	favoritesStore.delegate = delegate;
}

-(int)indexOfClipping:(NSString*)contents ofType:(NSString*)type fromApp:(NSString *)appName withAppBundleURL:(NSString *)bundleURL
{
	return [clippingStore indexOfClipping:contents
								   ofType:type
					 fromAppLocalizedName:appName
						 fromAppBundleURL:bundleURL
							  atTimestamp:[[NSDate date] timeIntervalSince1970]];
}

-(bool)addClipping:(NSString*)contents ofType:(NSString*)type fromApp:(NSString *)appName withAppBundleURL:(NSString *)bundleURL target:(id)selectorTarget clippingAddedSelector:(SEL)clippingAddedSelector
{
	if ( [clippingStore jcListCount] == 0 || ! [contents isEqualToString:[clippingStore clippingContentsAtPosition:0]]) {
		bool success = [clippingStore addClipping:contents
										   ofType:type
							 fromAppLocalizedName:appName
								 fromAppBundleURL:bundleURL
									  atTimestamp:[[NSDate date] timeIntervalSince1970]];

//		The below tracks our position down down down... Maybe as an option?
//		if ( [clippingStore jcListCount] > 1 ) stackPosition++;
		stackPosition = 0;
        [selectorTarget performSelector:clippingAddedSelector];
		[self actionAfterListModification];

		return success;
    }
	return  NO;
}

- (void)willDeleteClippingFromStore:(id)store AtIndex:(int)index {
	if ( (!inhibitAutosaveClippings) // Avoid saving things that the user explicitly deletes.
		&& ( store == favoritesStore
		? [[[NSUserDefaults standardUserDefaults] valueForKey:@"saveForgottenFavorites"] boolValue]
		: [[[NSUserDefaults standardUserDefaults] valueForKey:@"saveForgottenClippings"] boolValue] ) )
	{
		// clipping is being removed, so save it before it gets lost.
		// Set to last item, save, and restore position.
		[self saveFromStore:store atIndex:index withPrefix:@"Autosave "];
	}
}

-(void)actionAfterListModification
{
	if ( !inhibitSaveEngineAfterListModification
			&& [[NSUserDefaults standardUserDefaults] integerForKey:@"savePreference"] >= 2 )
			[self scheduleDeferredSaveEngine];
}

-(int)jcListCount
{
	return [clippingStore jcListCount];
}

-(int)rememberNum
{
	return [clippingStore rememberNum];
}

-(int)stackPosition
{
	return stackPosition;
}

-(bool)setStackPositionToFirstItem
{
	if ( [clippingStore jcListCount] > 0 ) {
		stackPosition = 0;
		return YES;
	}
	return NO;
}

-(bool)setStackPositionToLastItem
{
	if ( [clippingStore jcListCount] > 0 ) {
		stackPosition = [clippingStore jcListCount] - 1;
		return YES;
	}
	return NO;
}

-(bool)setStackPositionToTenMoreRecent
{
	if ( [clippingStore jcListCount] > 0 ) {
		stackPosition = stackPosition - 10; if ( stackPosition < 0 ) stackPosition = 0;
		return YES;
	}
	return NO;
}

-(bool)setStackPositionToTenLessRecent
{
	if ( [clippingStore jcListCount] > 0 ) {
		stackPosition = stackPosition + 10; if ( stackPosition >= [clippingStore jcListCount] ) stackPosition = [clippingStore jcListCount] - 1;
		return YES;
	}
	return NO;
}

-(bool)clearItemAtStackPosition
{
    if ([clippingStore jcListCount] == 0)
        return NO;

	inhibitAutosaveClippings = YES; // Avoid saving things that the user explicitly deletes.
	[clippingStore clearItem:stackPosition];
	inhibitAutosaveClippings = NO;
	[self actionAfterListModification];

    return YES;
}

-(bool)setStackPositionTo:(int) newStackPosition
{
	if ( [clippingStore jcListCount] >= newStackPosition ) {
		stackPosition = newStackPosition;
		return YES;
	}
	return NO;
}

// Would probably be good to just prevent this scenario where it originates and
// delete this check.
-(void)adjustStackPositionIfOutOfBounds
{
	if (stackPosition >= [clippingStore jcListCount] && stackPosition != 0) { // deleted last item
		stackPosition = [clippingStore jcListCount] - 1;
	}
}

-(bool)stackPositionIsInBounds
{
	return ( [clippingStore jcListCount] > 0 && [clippingStore jcListCount] > stackPosition );
}

-(void)clearList
{
    [clippingStore clearList];
    [self actionAfterListModification];
}

-(void)clearPrimaryList
{
	FloatcutStore *primaryStore = [self favoritesStoreIsSelected] ? stashedStore : clippingStore;
	if (!primaryStore)
		return;

	BOOL previousInhibitAutosave = inhibitAutosaveClippings;
	inhibitAutosaveClippings = YES;
	[primaryStore clearList];
	inhibitAutosaveClippings = previousInhibitAutosave;

	if (primaryStore == clippingStore)
		stackPosition = 0;
	else
		stashedStackPosition = 0;
	[self actionAfterListModification];
}

-(void)clearFavoritesList
{
	BOOL previousInhibitAutosave = inhibitAutosaveClippings;
	inhibitAutosaveClippings = YES;
	[favoritesStore clearList];
	inhibitAutosaveClippings = previousInhibitAutosave;

	if ([self favoritesStoreIsSelected])
		stackPosition = 0;
	else
		favoritesStackPosition = 0;
	[self actionAfterListModification];
}

-(void)mergeList
{
	[clippingStore mergeList];
	[self actionAfterListModification];
}

-(BOOL) isValidClippingNumber:(NSNumber *)number {
	return [self isValidClippingNumber:number inStore:clippingStore];
}

-(BOOL) isValidClippingNumber:(NSNumber *)number inStore:(FloatcutStore*)store {
    return ( ([number intValue] + 1) <= [store jcListCount] );
}

-(NSString *) clippingStringWithCount:(int)count {
	return [self clippingStringWithCount:count inStore:clippingStore];
}

-(NSString *) clippingStringWithCount:(int)count inStore:(FloatcutStore*)store {
    if ( [self isValidClippingNumber:[NSNumber numberWithInt:count] inStore:store] ) {
        return [store clippingContentsAtPosition:count];
    } else { // It fails -- we shouldn't be passed this, but...
        return @"";
    }
}

-(bool) loadEngineFrom:(NSDictionary*)loadDict key:(NSString*)listKey into:(FloatcutStore*)store
{
	NSArray *savedJCList = [loadDict objectForKey:listKey];
	if ( [savedJCList isKindOfClass:[NSArray class]] ) {
		// There's probably a nicer way to prevent the range from going out of bounds, but this works.
		int rangeCap = [savedJCList count] < [store rememberNum] ? [savedJCList count] : [store rememberNum];
		NSRange loadRange = NSMakeRange(0, rangeCap);
		NSArray *toBeRestoredClips = [[[savedJCList subarrayWithRange:loadRange] reverseObjectEnumerator] allObjects];
		for( NSDictionary *aSavedClipping in toBeRestoredClips) {
			FloatcutClipping *clipping = [[FloatcutClipping alloc] initWithContents:[aSavedClipping objectForKey:@"Contents"] ?: @""
														withType:[aSavedClipping objectForKey:@"Type"] ?: @""
												   withImageData:[aSavedClipping objectForKey:@"ImageData"]
											   withDisplayLength:[store displayLen]
											withAppLocalizedName:[aSavedClipping objectForKey:@"AppLocalizedName"]
												withAppBundleURL:[aSavedClipping objectForKey:@"AppBundleURL"]
											   withTimestamp:[[aSavedClipping objectForKey:@"Timestamp"] integerValue]];
			[clipping setIdentifier:[aSavedClipping objectForKey:@"Identifier"]];
			NSNumber *receivedFromSync = [aSavedClipping objectForKey:@"ReceivedFromSync"];
			NSString *savedAppName = [clipping appLocalizedName] ?: @"";
			[clipping setReceivedFromSync:receivedFromSync
				? [receivedFromSync boolValue]
				: [savedAppName hasPrefix:@"Sync: "]];
			// Preserve the previous loader's empty-text filtering while allowing
			// image clippings, whose textual contents are intentionally empty.
			if ([clipping isImage] || [[clipping contents] length] > 0)
				[store addClipping:clipping];
			[clipping release];
		}
		return YES;
	} else DLog(@"Not array");
	return NO;
}

-(bool) loadEngineFromPList
{
	NSDictionary *loadDict = [[[NSUserDefaults standardUserDefaults] dictionaryForKey:@"store"] copy];

	if ( loadDict != nil ) {
		bool success = NO;
		success |= [self loadEngineFrom:loadDict key:@"jcList" into:clippingStore];
		success |= [self loadEngineFrom:loadDict key:@"favoritesList" into:favoritesStore];
		[loadDict release];
		return success;
	}
	return NO;
}

-(bool)setStackPositionToOneLessRecent
{
	stackPosition++;
	if ( [clippingStore jcListCount] > stackPosition ) {
		return YES;
	} else {
		if ( [[NSUserDefaults standardUserDefaults] boolForKey:@"wraparoundBezel"] ) {
			stackPosition = 0;
			return YES;
		} else {
			stackPosition--;
		}
	}
	return NO;
}

-(bool)setStackPositionToOneMoreRecent
{
	stackPosition--;
	if ( stackPosition < 0 ) {
		if ( [[NSUserDefaults standardUserDefaults] boolForKey:@"wraparoundBezel"] ) {
			stackPosition = [clippingStore jcListCount] - 1;
			return YES;
		} else {
			stackPosition = 0;
			return NO;
		}
	}
	if ( [clippingStore jcListCount] > stackPosition ) {
		return YES;
	}
	return NO;
}

-(FloatcutClipping*)clippingAtStackPosition
{
    return [clippingStore clippingAtPosition:stackPosition];
}

- (void)saveStore:(FloatcutStore *)store toKey:(NSString *)key onDict:(NSMutableDictionary *)saveDict previousDict:(NSDictionary *)previousDict {
	if (![store modifiedSinceLastSaveStore]) {
		NSArray *previousArray = [previousDict objectForKey:key];
		[saveDict setObject:previousArray ?: [NSArray array] forKey:key];
		return;
	}

    NSMutableArray *jcListArray = [NSMutableArray array];
    for ( int i = 0 ; i < [store jcListCount] ; i++ )
    {
        FloatcutClipping *clipping = [store clippingAtPosition:i];
        NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithObjectsAndKeys:
                                     [clipping contents], @"Contents",
                                     [clipping type], @"Type",
                                     [NSNumber numberWithInt:i], @"Position",nil];

		NSString *val = [clipping appLocalizedName];
        if ( nil != val )
            [dict setObject:val forKey:@"AppLocalizedName"];

        val = [clipping appBundleURL];
        if ( nil != val )
            [dict setObject:val forKey:@"AppBundleURL"];

        NSData *imageData = [clipping imageData];
        if ( nil != imageData )
            [dict setObject:imageData forKey:@"ImageData"];

        int timestamp = [clipping timestamp];
		if ( timestamp > 0 )
			[dict setObject:[NSNumber numberWithInt:timestamp] forKey:@"Timestamp"];

		val = [clipping identifier];
		if ([val length] > 0)
			[dict setObject:val forKey:@"Identifier"];

		if ([clipping receivedFromSync])
			[dict setObject:[NSNumber numberWithBool:YES] forKey:@"ReceivedFromSync"];

        [jcListArray addObject:dict];
    }
    [saveDict setObject:jcListArray forKey:key];
	[store clearModifiedSinceLastSaveStore];
}

-(void) saveEngine {
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(runDeferredSaveEngine) object:nil];
    pendingDeferredSave = NO;

	// saveEngine saves to NSUserDefaults.  If there have been no modifications, just skip this to avoid busy activity for any observers.
	if ( !([clippingStore modifiedSinceLastSaveStore]
		   || [favoritesStore modifiedSinceLastSaveStore]) )
		return;

#if FLOATCUT_PERFORMANCE_TESTING
    NSTimeInterval snapshotStart = [NSProcessInfo processInfo].systemUptime;
#endif

	NSMutableDictionary *saveDict;
    saveDict = [NSMutableDictionary dictionaryWithCapacity:3];
    [saveDict setObject:@"0.7" forKey:@"version"];
    [saveDict setObject:[NSNumber numberWithInt:[[NSUserDefaults standardUserDefaults] integerForKey:@"rememberNum"]]
                 forKey:@"rememberNum"];
    [saveDict setObject:[NSNumber numberWithInt:[[NSUserDefaults standardUserDefaults] integerForKey:@"favoritesRememberNum"]]
                 forKey:@"favoritesRememberNum"];

	[saveTarget performSelector:saveSelector withObject:saveDict];

	NSDictionary *previousDict = [[NSUserDefaults standardUserDefaults] dictionaryForKey:@"store"];
	[self saveStore:clippingStore toKey:@"jcList" onDict:saveDict previousDict:previousDict];
	[self saveStore:favoritesStore toKey:@"favoritesList" onDict:saveDict previousDict:previousDict];

#if FLOATCUT_PERFORMANCE_TESTING
    NSTimeInterval snapshotEnd = [NSProcessInfo processInfo].systemUptime;
#endif
	[[NSUserDefaults standardUserDefaults] setObject:saveDict forKey:@"store"];
#if FLOATCUT_PERFORMANCE_TESTING
    NSTimeInterval defaultsEnd = [NSProcessInfo processInfo].systemUptime;
#endif
	[[NSUserDefaults standardUserDefaults] synchronize];
#if FLOATCUT_PERFORMANCE_TESTING
    NSTimeInterval syncEnd = [NSProcessInfo processInfo].systemUptime;
    NSLog(@"Persistence benchmark: snapshot=%.3f setObject=%.3f synchronize=%.3f total=%.3f ms",
          (snapshotEnd - snapshotStart) * 1000, (defaultsEnd - snapshotEnd) * 1000,
          (syncEnd - defaultsEnd) * 1000, (syncEnd - snapshotStart) * 1000);
#endif
}

- (void)scheduleDeferredSaveEngine
{
    pendingDeferredSave = YES;
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(runDeferredSaveEngine) object:nil];
    [self performSelector:@selector(runDeferredSaveEngine)
               withObject:nil
               afterDelay:FloatcutDeferredSaveDelay
                  inModes:@[NSRunLoopCommonModes]];
}

- (void)runDeferredSaveEngine
{
    if (!pendingDeferredSave)
        return;

    pendingDeferredSave = NO;
    [self saveEngine];
}

-(void)prepareForMigrationRestart
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(runDeferredSaveEngine) object:nil];
    pendingDeferredSave = NO;
    suppressNextTerminationSave = YES;
}

- (void)applicationWillTerminate {
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(runDeferredSaveEngine) object:nil];
    pendingDeferredSave = NO;

    if (suppressNextTerminationSave)
        return;

	if ( [[NSUserDefaults standardUserDefaults] integerForKey:@"savePreference"] >= 1 ) {
		DLog(@"Saving on exit");
        [self saveEngine];
    } else {
        // Remove clips from store
        [[NSUserDefaults standardUserDefaults] setValue:[NSDictionary dictionary] forKey:@"store"];
        DLog(@"Saving preferences on exit");
        [[NSUserDefaults standardUserDefaults] synchronize];
    }
}

-(NSArray *) previousIndexes:(int)howMany containing:(NSString*)search // This method is in newest-first order.
{
	return [clippingStore previousIndexes:howMany containing:search];
}

-(NSArray *) previousDisplayStrings:(int)howMany containing:(NSString*)search
{
	return [clippingStore previousDisplayStrings:howMany containing:search];
}

-(NSString*) delegateAlertWithMessageText:(NSString*)message informationText:(NSString*)information buttonsTexts:(NSArray*)buttons
{
	if ( self.delegate && [self.delegate respondsToSelector:@selector(alertWithMessageText:informationText:buttonsTexts:)] )
		return [self.delegate alertWithMessageText:message informationText:information buttonsTexts:buttons];
	return nil;
}

@end
